import type { GameConfig } from "@/types";
import { GAME_MECHANICS, TIMING } from "@/config/gameConfig";

export const VIBE_CARDS = [
	"A heartbreaking Country ballad about ______",
	"An upbeat Pop anthem celebrating ______",
	"A dramatic Rock opera about ______",
	"A smooth Jazz number about ______",
	"A rebellious Punk song screaming about ______",
	"A soulful R&B jam dedicated to ______",
	"A sad Emo ballad crying over ______",
	"An aggressive Death Metal song destroying ______",
	"A romantic Slow Jam about ______",
	"A club-banging EDM track about ______",
	"A melancholic Indie song reflecting on ______",
	"A triumphant Gospel choir praising ______",
	"A gangsta Rap verse flexing on ______",
	"A twangy Bluegrass tune about ______",
	"A haunting Goth anthem mourning ______",
	"A cheerful K-Pop bop about ______",
	"A psychedelic Rock song tripping on ______",
	"A sexy Latin Reggaeton jam about ______",
	"A depressing Shoegaze track drowning in ______",
	"A hype Trap song about ______",
	"An emotional Power Ballad about ______",
	"A chill Lo-fi Hip-Hop beat about ______",
	"A theatrical Broadway show tune about ______",
	"An angry Hardcore song raging against ______",
	"A dreamy Synthwave anthem about ______",
	"A sad Folk song with harmonica about ______",
	"A filthy Dirty South rap about ______",
	"A nostalgic 80s Synthpop song about ______",
	"A spiritual Hymn worshipping ______",
	"A bouncy Reggae song chilling with ______",
	"A pretentious Art Rock piece about ______",
	"A raunchy Blues number about ______",
	"An intense Drill rap about ______",
	"A whimsical Children's song teaching about ______",
	"A depressing Grunge song hating ______",
	"A motivational Workout anthem pumping up ______",
	"A spooky Horror Movie theme about ______",
	"A sweet Lullaby for ______",
	"An epic Viking Metal song conquering ______",
	"A sassy Diss Track roasting ______",
	"A classy Opera aria lamenting ______",
	"A groovy Disco hit dancing to ______",
	"A crude Parody song mocking ______",
	"A tender Love Song confessing feelings for ______",
	"An awkward Nerdcore rap about ______",
	"A chaotic Experimental Noise track about ______",
	"A sarcastic Indie Rock song about ______",
	"A sultry Burlesque number teasing ______",
	"A depressing Funeral Doom dirge for ______",
	"A boastful Swagger Rap about ______",
	"An innocent Acoustic Campfire song about ______",
	"A rowdy Sea Shanty about ______",
	"A heartfelt Apology Song for ______",
	"A vengeful Breakup Anthem cursing ______",
	"A bizarre Carnival Music piece about ______",
	"An inspiring Motivational Speech about ______",
	"A cringey Corporate Jingle selling ______",
	"A wild Party Anthem getting wasted on ______",
	"A meditative Ambient soundscape exploring ______",
	"A ratchet Twerk anthem shaking ______",
	"A paranoid Conspiracy Theory rant about ______",
	"A wholesome Mr. Rogers song about ______",
	"A shameful Confession Song about ______",
	"An epic Anime Opening about ______",
	"A sketchy Drug Dealer rap about ______",
	"A cringe TikTok Song about ______",
	"A depressing Existential Crisis song about ______",
	"A horny Late Night Slow Jam about ______",
	"An unhinged Villain Song plotting ______",
	"A guilty Drunk Text turned into song about ______",
	"A toxic Love Song obsessing over ______",
	"An awkward Middle School Dance slow song about ______",
	"A regretful Morning After song about ______",
	"An aggressive Road Rage anthem about ______",
	"A culty Religious Chant worshipping ______",
	"A desperate Booty Call song about ______",
	"An embarrassing Karaoke performance of ______",
	"A sad Friendzone Lament about ______",
	"A sketchy Back Alley Deal song about ______",
	"A creepy Stalker Ballad about ______",
	"An insufferable Hipster song ironically enjoying ______",
	"A chaotic Florida Man news story about ______",
	"A forbidden Office Romance song about ______",
	"A suspicious MLM Pitch song about ______",
	"An oversharing Therapy Session song about ______",
	"A messy Divorce Proceedings song about ______",
	"A cringe LinkedIn Influencer post about ______",
	"A desperate Dating App bio song about ______",
	"An unhinged Reddit Moderator anthem about ______",
	"A questionable Life Coach seminar about ______",
	"A delusional Crypto Bro anthem about ______",
	"An uncomfortable Family Dinner conversation about ______",
	"A petty Yelp Review song about ______",
	"A passive-aggressive HOA Notice about ______",
	"A dramatic True Crime Podcast about ______",
	"An existential 3am Thoughts song about ______",
	"A chaotic Bachelor Party gone wrong song about ______",
	"A regrettable Spring Break anthem about ______",
	"An awkward Parent-Teacher Conference about ______",
] as const;

export const LYRIC_CARDS = [
	"pizza delivery gone wrong",
	"my neighbor's suspicious garden gnome",
	"forgetting pants on Zoom",
	"arguing with a vending machine",
	"my cat's secret double life",
	"existential dread at the DMV",
	"losing a fight with IKEA furniture",
	"accidentally joining a cult",
	"my embarrassing browser history",
	"becoming a meme",
	"talking to plants (they talk back)",
	"the conspiracy of missing socks",
	"road rage in bumper cars",
	"my therapist's therapist",
	"accidentally becoming TikTok famous",
	"questioning my life choices at 3am",
	"the audacity of geese",
	"passive-aggressive post-it notes",
	"my FBI agent watching through my webcam",
	"emotional support peacock",
	"catfishing myself on Tinder",
	"weaponized incompetence",
	"the friend zone (I live there now)",
	"chronic main character syndrome",
	"gaslighting my Alexa",
	"my parasocial relationship with celebrities",
	"Hot Girl Summer (I failed)",
	"being cancelled on Twitter",
	"unhinged LinkedIn posts",
	"my toxic trait",
	"manifesting bad bitches",
	"goblin mode activated",
	"the walk of shame",
	"drunk texting my ex",
	"shower thoughts that keep me up",
	"intrusive thoughts winning",
	"emotional damage",
	"the ick",
	"rizz (or lack thereof)",
	"red flags I ignored",
	"attachment issues",
	"daddy issues manifesting",
	"mommy's credit card",
	"trust fund problems",
	"getting humbled",
	"touch grass (I should)",
	"unresolved childhood trauma",
	"my crippling Reddit addiction",
	"broke and unbothered",
	"sugar daddy applications",
	"my OnlyFans career",
	"side hustles that failed",
	"crypto losses",
	"NFTs I regret buying",
	"gambling problem disguised as investing",
	"tax evasion (hypothetically)",
	"money laundering for dummies",
	"pyramid scheme energy",
	"multi-level marketing my friends",
	"insurance fraud thoughts",
	"faking my own death",
	"witness protection program fantasies",
	"running away to join the circus",
	"becoming a hermit in the woods",
	"my murder podcast obsession",
	"true crime brain rot",
	"serial killer documentaries at bedtime",
	"morbid curiosity",
	"Wikipedia rabbit holes at 4am",
	"conspiracy theories I believe",
	"the Illuminati (they're watching)",
	"chemtrails and government lies",
	"birds aren't real",
	"flat Earth Facebook groups",
	"vaccines turned me magnetic",
	"microchips in the COVID shot",
	"5G towers controlling minds",
	"lizard people in Congress",
	"astrology as a personality",
	"Mercury retrograde excuses",
	"manifesting toxicity",
	"crystals solving nothing",
	"sage burning my problems away",
	"tarot cards roasting me",
	"my rising sign's fault",
	"birth chart incompatibility",
	"toxic positivity",
	"hustle culture breakdown",
	"gaslight gatekeep girlboss",
	"living my worst life",
	"self-care is a scam",
	"therapy can't fix this",
	"medicate don't meditate",
	"wine mom energy",
	"day drinking socially acceptable hours",
	"blacking out respectfully",
	"hangover regrets",
	"questionable decisions while drunk",
	"drunk Amazon purchases",
	"ordering Uber Eats at 2am",
	"eating feelings",
	"stress eating an entire cake",
	"binge eating in my car",
	"faking food allergies",
	"lying about being vegan",
	"cheat days that never end",
	"body dysmorphia in dressing rooms",
	"Spanx cutting off circulation",
	"Photoshopping my Instagram",
	"filters hiding my real face",
	"facetune addiction",
	"unrealistic beauty standards",
	"cosmetic surgery gone wrong",
	"Botox paralyzed my face",
	"filler migration",
	"BBL complications",
	"Brazilian wax trauma",
	"laser hair removal regrets",
	"spray tan disasters",
	"hair extensions falling out",
	"lash extensions poking my eye",
	"acrylic nails as weapons",
	"infected piercings",
	"tattoo regret",
	"cover-up tattoos of cover-ups",
	"tramp stamp from 2005",
	"neck tattoo job interview",
	"face tattoo consequences",
	"prison tattoos without prison time",
	"matching tattoos with exes",
	"your name on my body (mistake)",
	"laser tattoo removal pain",
	"commitment issues with haircuts",
	"bad haircut depression",
	"mullet revival",
	"bleach damaged hair falling out",
	"bald spots and toupees",
	"receding hairline at 25",
	"male pattern baldness denial",
	"thinning hair coping mechanisms",
	"wig snatching drama",
	"weave tracks showing",
	"midlife crisis makeover",
	"Rogaine dependency",
	"hair plugs looking suspicious",
	"comb-over fooling nobody",
	"premature ejaculation",
	"erectile dysfunction",
	"whiskey dick",
	"performance anxiety",
	"disappointing size",
	"overcompensating with a truck",
	"small dick energy",
	"big dick energy (unearned)",
	"penis enlargement spam emails",
	"Viagra dependency",
	"Cialis commercial feelings",
	"blue balls syndrome",
	"post-nut clarity",
	"refractory period depression",
	"masturbation guilt",
	"chronic masturbator",
	"death grip syndrome",
	"porn addiction ruining relationships",
	"weird fetishes I can't explain",
	"kink shaming myself",
	"safe word misunderstandings",
	"BDSM injuries requiring ER visit",
	"furry conventions",
	"cosplay gone sexual",
	"anime body pillows",
	"hentai preferences",
	"rule 34 discoveries",
	"OnlyFans subscriptions I'm hiding",
	"Pornhub premium worth it",
	"incognito mode mistakes",
	"clearing browser history frantically",
	"getting caught watching",
	"walked in during the act",
	"roommate hearing through walls",
	"parents finding my toys",
	"vibrator batteries dying",
	"sex shop embarrassment",
	"ordering toys to wrong address",
	"Amazon delivering dildos to neighbors",
	"TSA finding toys in luggage",
	"customs inspecting my imports",
	"explaining to grandma",
	"family finding my OnlyFans",
	"coworkers discovering my side gig",
	"boss finding my social media",
	"LinkedIn request from one night stand",
	"HR meeting about conduct",
	"sexual harassment seminar",
	"uncomfortable workplace relationships",
	"office affair consequences",
	"hooking up at company retreat",
	"Christmas party regrets",
	"sleeping with my boss",
	"banging the intern",
	"workplace romance policy violations",
	"getting fired for fraternization",
	"unemployment benefits appeal",
	"job searching while employed",
	"faking references",
	"lying on my resume",
	"degree mill diploma",
	"forging credentials",
	"pretending to know Excel",
	"Googling during interview",
	"showing up drunk to work",
	"microdosing at the office",
	"Adderall keeping me productive",
	"cocaine business meetings",
	"molly at music festivals",
	"acid trips gone wrong",
	"shrooms revealing the truth",
	"DMT entity encounters",
	"ayahuasca purging ceremony",
	"ketamine therapy sessions",
	"prescription pill dependency",
	"Xanax blackouts",
	"mixing benzos and alcohol",
	"oxy addiction timeline",
	"fentanyl test strips",
	"Narcan in my purse",
	"rehab for the third time",
	"sober living house rules",
	"AA meeting hookups",
	"NA sponsor boundaries",
	"relapse excuses",
	"celebrating one day sober",
	"counting days not years",
	"addiction replacing addiction",
	"cigarettes after quitting drinking",
	"vaping to quit smoking",
	"Juul pods everywhere",
	"nicotine pouch addiction",
	"Zyn rotting my gums",
	"chain smoking anxiety away",
	"smoking in no-smoking areas",
	"cigarette burns in rental car",
	"fire alarm from hotboxing",
	"neighbors complaining about weed smell",
	"edibles hitting too hard",
	"greening out at dinner",
	"paranoia after smoking",
	"weed-induced anxiety attack",
	"dab rig explosion",
	"caught with paraphernalia",
	"drug test panic",
	"fake pee tutorial",
	"probation violations",
	"ankle monitor chafing",
	"house arrest boredom",
	"court-mandated therapy",
	"community service in orange vest",
	"public defender disappointment",
	"jail time for something stupid",
	"county jail food",
	"prison pen pal romance",
	"conjugal visit awkwardness",
	"parole officer power trips",
	"restraining order violations",
	"protective order against me",
	"no-contact order temptation",
	"toxic relationship cycles",
	"breaking up to make up",
	"on-again off-again exhaustion",
	"relationship hopping",
	"serial monogamist problems",
	"commitment phobe diagnosis",
	"fear of being alone",
	"settling for less than I deserve",
	"staying for the wrong reasons",
	"sunk cost fallacy relationships",
	"trauma bonding explained",
	"codependency issues",
	"love bombing red flags",
	"breadcrumbing behavior",
	"ghosting after three months",
	"zombie-ing exes",
	"haunting old flames",
	"orbiting on social media",
	"soft launching new relationship",
	"hard launching too soon",
	"posting for one person to see",
	"couple photos I'll regret",
	"matching tattoos before marriage",
	"engagement after three months",
	"wedding planning arguments",
	"cold feet at altar",
	"runaway bride fantasies",
	"divorce attorneys on speed dial",
	"prenup negotiations",
	"cheating suspicions",
	"finding Tinder on their phone",
	"Ashley Madison account discovered",
	"secret second family",
	"affair baby revelation",
	"paternity test results",
	"DNA surprise ancestry",
	"finding out I'm adopted",
	"estranged family drama",
	"inheritance disputes",
	"will reading betrayals",
	"funeral drama and fights",
	"grave dancing on enemies",
	"speaking ill of the dead",
	"cremation urn mishaps",
	"scattering ashes gone wrong",
	"coffin selfies",
	"wake getting too turnt",
	"inappropriate eulogy",
	"laughing at funeral",
	"funeral crashers",
	"grief tourists",
	"mourning for attention",
	"using death for clout",
	"faking deaths on social media",
	"suicide baiting for sympathy",
	"mental health faking",
	"Munchausen by internet",
	"chronic illness influencers",
	"wheelchair for Disney FastPass",
	"faking service dog papers",
	"emotional support alligator",
	"therapy peacock on plane",
	"airport security meltdown",
	"no-fly list appearance",
	"TSA pat-down trauma",
	"customs cavity search",
	"smuggling contraband internationally",
	"trafficking charges misunderstanding",
	"international incident I caused",
	"deported from foreign country",
	"blacklisted from entire nation",
	"Interpol warrant possibly",
	"fleeing jurisdiction",
	"skipping bail consequences",
	"manhunt for unpaid parking tickets",
	"warrant for my arrest",
	"wanted in three states",
	"alias I've been using",
	"fake ID usage",
	"identity theft victim",
	"credit card fraud victim",
	"Nigerian prince scam almost",
	"phishing email I fell for",
	"ransomware on my computer",
	"leaked nudes nightmare",
	"revenge porn revenge",
	"deepfake of me existing",
	"AI-generated scandalous content",
	"chatbot replacing my job",
	"robot uprising I predicted",
	"Skynet becoming self-aware",
	"technological singularity anxiety",
	"AI girlfriends replacing real ones",
	"VR addiction and isolation",
	"metaverse real estate regrets",
	"virtual reality motion sickness",
	"simulation theory proof",
	"living in the Matrix",
	"glitch revealing it's fake",
	"NPC behavior in others",
	"deja vu frequency increase",
	"Mandela Effect memories",
	"alternative timeline I remember",
	"quantum immortality theory",
	"multiverse of bad decisions",
	"parallel universe where I'm successful",
	"timeline where I'm happy",
	"alternate reality nostalgia",
	"the one that got away",
	"right person wrong time",
	"what could have been",
	"paths not taken",
	"opportunities I missed",
	"talent I wasted",
	"potential I squandered",
	"dreams I abandoned",
	"giving up too easily",
	"quitter mentality",
	"participation trophy generation",
	"everyone gets a medal culture",
	"entitlement issues",
	"main character syndrome peak",
	"the world revolving around me",
	"selfish tendencies unchecked",
	"narcissistic personality traits",
	"undiagnosed mental illness",
	"self-diagnosing on WebMD",
	"hypochondriac spiral",
	"health anxiety convincing me",
	"rare disease I definitely have",
	"terminal illness fears",
	"death anxiety consuming me",
	"mortality crisis at 30",
	"quarter-life crisis breakdown",
	"mid-life crisis early",
	"buying a sports car can't afford",
	"hair transplant in Turkey",
	"plastic surgery tourism",
	"botched procedures abroad",
	"medical malpractice abroad",
	"unregulated cosmetic procedures",
	"black market Botox",
	"sketchy injections in basement",
	"fillers from questionable source",
	"silicone shots gone wrong",
	"illegal butt injections",
	"DIY cosmetic surgery",
	"bathroom tummy tuck",
	"performing own vasectomy",
	"home lobotomy kit",
	"self-surgery complications",
	"stitching myself up",
	"superglue closing wounds",
	"duct tape solving problems",
	"redneck engineering solutions",
	"hillbilly ingenuity",
	"Florida Man headlines featuring me",
	"methamphetamine laboratory neighbors",
	"trailer park drama",
	"Jerry Springer episode material",
	"Maury Povich paternity reveal",
	"you are NOT the father",
	"surprise baby mama",
	"child support dodging",
	"deadbeat dad energy",
	"absentee parent guilt",
	"kids I forgot about",
	"family I abandoned",
	"running from responsibility",
	"Peter Pan syndrome",
	"refusing to grow up",
	"adulting is hard",
	"taxes I haven't filed",
	"IRS auditing my returns",
	"wage garnishment notices",
	"collections agencies calling",
	"bankruptcy filing number three",
	"foreclosure proceedings",
	"eviction notice countdown",
	"squatters rights research",
	"living in my car",
	"tent city residency",
	"homelessness just around corner",
	"couch surfing indefinitely",
	"crashing at mom's again",
	"basement dwelling at 40",
	"failure to launch syndrome",
] as const;

export const DEFAULT_GAME_CONFIG: GameConfig = {
	timerDuration: GAME_MECHANICS.timerDuration,
	handSize: GAME_MECHANICS.handSize,
};

export const GAME_CONSTANTS = {
	GENERATION_INTERVAL: TIMING.generationInterval,
	GENERATION_INCREMENT: TIMING.generationIncrement,
	AUTO_SUBMIT_DELAY: TIMING.autoSubmitDelay,
	PHASE_TRANSITION_DELAY: TIMING.phaseTransitionDelay,
	PROGRESS_UPDATE_INTERVAL: TIMING.progressUpdateInterval,
} as const;
